[project]
name = "feishu-easy"
version = "0.2.3"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "niu2x", email = "niu2x@icloud.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "filetype>=1.2.0",
    "imagesize>=2.0.0",
    "lark-oapi==1.6.5",
    "tenacity>=9.1.4",
    "typer>=0.24.1",
    "pydantic>=2.12.5",
    "markcraft>=1.0.1",
    "Pillow>=10.0.0",
]

[project.scripts]
feishu-easy = "feishu_easy:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[[tool.uv.index]]
url = "https://pypi.org/simple"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.15.8",
    "twine>=6.2.0",
]
