from __future__ import annotations

WIKI_LIST_SPACE_PAGE_SIZE = 10
WIKI_LIST_SPACE_MEMBER_PAGE_SIZE = 50
WIKI_LIST_SPACE_NODE_PAGE_SIZE = 50
DRIVE_LIST_FILE_PAGE_SIZE = 50
DRIVE_LIST_FILE_VERSION_PAGE_SIZE = 50
DRIVE_LIST_FILE_VIEW_RECORD_PAGE_SIZE = 50
TOKEN_REFRESH_EARLY_SECONDS = 1800
FEISHU_RATE_LIMIT_ERROR_CODES = {99991400, 1061045}
